---
# Generate the Linux login banner content by rendering the 'issue.j2' template
# This content can be customized by providing your own template
banner_content: "{{ '\n' ~ lookup('ansible.builtin.template', 'issue.j2') ~ '\n' }}"
