---
# Generate the Linux login banner content by rendering the 'issue.j2' template
# This content can be customized by providing your own template
banner_content_issue: "{{ '\n' ~ lookup('ansible.builtin.template', 'issue.j2') ~ '\n' }}"

# Define the custom content for the Linux message of the day (MOTD)
# By default, setting this value to an empty string will clear the existing MOTD content.
banner_content_motd: ""
